### ISSUE TITLE
你好,发现Typecho的Pinghsu主题和你的插件冲突

### ISSUE THREAD

**Issue by of0** [hongweipeng/CodeStyle#3]
你好,发现Typecho的Pinghsu主题和你的插件冲突,切换样式没有效果,有解决办法吗?

**Comment by hongweipeng** [comment]
Pinghsu主题的样式中已经一定了代码块的样式，并且还引入一个xcode风格的css。肯定是冲突的。

**Comment by hongweipeng** [comment]
![20180503175637](https://user-images.githubusercontent.com/7546325/39570589-584d33f2-4efb-11e8-8d3b-2d507c8a316d.png)

代码样式已在主题里定义了哦。

**Comment by of0** [comment]
谢谢回复,有办法替换Pingshu的显示吗

**Comment by hongweipeng** [comment]
我的插件也是用 HighlightJS 来进行高亮现实的，理论上你不用替换。要替换的话你还得改代码，把主题上找到并删除引用高亮js和代码样式css。感觉没必要，这个插件用的也是这个高亮库，既然主题具备了，就不用多此一举了我觉得

**Comment by of0** [comment]
嗯,不过我是用的H-CODE这款主题..它的MD样式很奇葩
不过我已经修改了部分CSS样式,现在效果还较满意.
感谢回复
