### ISSUE TITLE
代码显示缺失

### ISSUE THREAD

**Issue by youfuyu** [hongweipeng/CodeStyle#5]
作者你好，发现了一个bug
正常打开代码显示有丢失
![qq 20190104134555](https://user-images.githubusercontent.com/38101612/50675176-4b9f2280-1027-11e9-862e-db0117a19b10.png)
刷新的一瞬间是这样的
![qq 20190104134622](https://user-images.githubusercontent.com/38101612/50675186-55c12100-1027-11e9-8ec4-05d282d30692.png)

**Comment by hongweipeng** [comment]
样式渲染是前端js完成的，如果你页面有其他地方js报错，后续的js是不会执行的。

**Comment by youfuyu** [comment]
我用的就是作者你的greengrape主题啊，不过确实检查到了js错误
![1](https://user-images.githubusercontent.com/38101612/50724174-23491e00-1124-11e9-9339-ef8ebd9462d0.PNG)

**Comment by hongweipeng** [comment]
这个报错是没有找到dom元素，所以`getElemntsByClassName`就为空了。你是不是顶部的粒子效果的那个元素有修改了啊

**Comment by youfuyu** [comment]
我从github上clone之后就没有修改过源码啊

**Comment by youfuyu** [comment]
错误原因是我在设置里面勾上了文章页隐藏头像，不勾上就没有报错了，但是代码显示还是跟之前一样有缺失

**Comment by hongweipeng** [comment]
隐藏头像的问题我可以调整下。代码高亮那块记得之前有人反应，他是因为用了 `EditMD` 插件，把插件的选项 "接管前台Markdown解析" 设置成否就可以了。

**Comment by youfuyu** [comment]
好像就那一篇文章那儿出问题了，其他文章正常，可能是特殊符号的原因吧，之前我发现有代码的宏定义显示不正常。
然后还发现一个问题就是代码隐藏着的那一部分背景没有得到渲染
![2](https://user-images.githubusercontent.com/38101612/50726311-2fde6e00-1146-11e9-93cf-531b3ff2b7bf.PNG)

**Comment by hongweipeng** [comment]
文章页隐藏头像是主题的问题，我在 [373647d](https://github.com/hongweipeng/GreenGrapes/commit/373647dffa4fcd390cd22fccdb19e31aed9adf19) 进行修复了，谢谢反馈。

背景没有得到渲染的问题，你能留个博客地址之类的吗我看看情况。因为我这边即使代码块不设置自动换行也是可以渲染的。

**Comment by hongweipeng** [comment]
我这边的这样的。

![gif](https://user-images.githubusercontent.com/7546325/50731724-c04c9b00-11a6-11e9-93e0-c9e0294c86e9.gif)

**Comment by youfuyu** [comment]
https://www.noncoeur.com/archives/centos7-lamp.html
谢谢啦

**Comment by hongweipeng** [comment]
我本地也复现了，就默认配色方案宽度超出部分会失效。现已进行了修复。感谢您的反馈。
